name: DonatorReclaim
version: ${version}
main: nl.chimpgamer.donatorreclaim.DonatorReclaim
authors: [ChimpGamer]
api-version: '1.13'

commands:
  reclaim:
    description: Reclaim your rewards as donator.
    permission: donatorreclaim.commands.reclaim