onlyReclaimHighestRank: false
executeRedeemOnFirstJoin: false
reclaimSound: 'ENTITY_PLAYER_LEVELUP'

ranks:
  vip:
    permission: 'donatorreclaim.rank.vip'
    commands:
    - broadcast %playername% has redeemed his %rank% rank!
  god:
    permission: 'donatorreclaim.rank.god'
    commands:
    - broadcast %playername% has redeemed his %rank% rank!